export const cryptosConstants = {
    GET_CRYPTOS_REQUEST: "GET_CRYPTOS_REQUEST",
    GET_CRYPTOS_SUCCESS: "GET_CRYPTOS_SUCCESS",
    GET_CRYPTOS_FALIURE: "GET_CRYPTOS_FALIURE",
    GET_CRYPTOS_UPDATE_ITEM: 'GET_CRYPTOS_UPDATE_ITEM'
};