export const accountsConstants = {
    GET_ACCOUNTS_REQUEST: "GET_ACCOUNTS_REQUEST",
    GET_ACCOUNTS_SUCCESS: "GET_ACCOUNTS_SUCCESS",
    GET_ACCOUNTS_FAILURE: "GET_ACCOUNTS_FAILURE",
    GET_ACCOUNTS_UPDATE_ITEM: 'GET_ACCOUNTS_UPDATE_ITEM',
};