export const accountsConstants = {
    GET_ACCOUNTS_REQUEST: "GET_ACCOUNTS_REQUEST",
    GET_ACCOUNTS_SUCCESS: "GET_ACCOUNTS_SUCCESS",
    GET_ACCOUNTS_FAILURE: "GET_ACCOUNTS_FAILURE",
    GET_ACCOUNTS_UPDATE_ITEM: 'GET_ACCOUNTS_UPDATE_ITEM',

    GET_DEFAULT_ARRAYS: "GET_DEFAULT_ARRAYS",
    GET_DEFAULT_ARRAYS_SUCCESS: "GET_DEFAULT_ARRAYS_SUCCESS",
    GET_DEFAULT_ARRAYS_FAILURE: "GET_DEFAULT_ARRAYS_FAILURE"
};