export const defaultsConstants = {
    GET_DEFAULT_ARRAYS: "GET_DEFAULT_ARRAYS",
    GET_DEFAULT_ARRAYS_SUCCESS: "GET_DEFAULT_ARRAYS_SUCCESS",
    GET_DEFAULT_ARRAYS_FAILURE: "GET_DEFAULT_ARRAYS_FAILURE",
    GET_DEFAULT_UPDATE_ITEM: "GET_DEFAULT_UPDATE_ITEM"
}