export const reconcileConstants = {
    GET_RECONCILE_REQUEST: 'GET_RECONCILE_REQUEST',
    GET_RECONCILE_SUCCESS: 'GET_RECONCILE_SUCCESS',
    GET_RECONCILE_FAILURE: 'GET_RECONCILE_FAILURE',
    GET_RECONCILE_TICKLIST: 'GET_RECONCILE_TICKLIST',
    UPDATE_RECONCILE_TICKLIST: 'UPDATE_RECONCILE_TICKLIST',
    SET_RECONCILE_SELECTED_ENTRIES: 'SET_RECONCILE_SELECTED_ENTRIES',
    SET_RECONCILE_MONTH: 'SET_RECONCILE_MONTH',
    SET_RECONCILE_YEAR: 'SET_RECONCILE_YEAR'
};
