export const regtransConstants = {
    GET_REGTRANS_REQUEST: "GET_REGTRANS_REQUEST",
    GET_REGTRANS_SUCCESS: "GET_REGTRANS_SUCCESS",
    GET_REGTRANS_FAILURE: "GET_REGTRANS_FAILURE",
    GET_REGTRANS_UPDATE_ITEM: 'GET_REGTRANS_UPDATE_ITEM',
    UPDATE_REGTRANS_CHECKED_STATE: "UPDATE_REGTRANS_CHECKED_STATE"
};