export const regtransConstants = {
    GET_REGTRANS_REQUEST: 'GET_REGTRANS_REQUEST',
    GET_REGTRANS_SUCCESS: 'GET_REGTRANS_SUCCESS',
    GET_REGTRANS_FAILURE: 'GET_REGTRANS_FAILURE',
    GET_REGTRANS_TICKLIST: 'GET_REGTRANS_TICKLIST',
    UPDATE_REGTRANS_TICKLIST: 'UPDATE_REGTRANS_TICKLIST',
    SET_REGTRANS_SELECTED_ENTRIES: 'SET_REGTRANS_SELECTED_ENTRIES',
    SET_REGTRANS_MONTH: 'SET_REGTRANS_MONTH',
    SET_REGTRANS_YEAR: 'SET_REGTRANS_YEAR'
};
