export const regtransConstants = {
    GET_REGTRANS_REQUEST: "GET_REGTRANS_REQUEST",
    GET_REGTRANS_SUCCESS: "GET_REGTRANS_SUCCESS",
    GET_REGTRANS_FAILURE: "GET_REGTRANS_FAILURE",
    GET_REGTRANS_UPDATE_ITEM: 'GET_REGTRANS_UPDATE_ITEM',
    GET_REGTRANS_TICKLIST: "GET_REGTRANS_TICKLIST",
    UPDATE_REGTRANS_TICKLIST: "UPDATE_REGTRANS_TICKLIST"
};