export const transactionsConstants = {
    GET_TRANSACTIONS_REQUEST: 'GET_TRANSACTIONS_REQUEST',
    GET_TRANSACTIONS_SUCCESS: 'GET_TRANSACTIONS_SUCCESS',
    GET_TRANSACTIONS_FAILURE: 'GET_TRANSACTIONS_FAILURE',
    GET_TRANSACTION_SEARCH_QUERY: 'GET_TRANSACTION_SEARCH_QUERY',
    GET_MATCHING_DESCRIPTION_DATA: 'GET_MATCHING_DESCRIPTION_DATA',
    CLEAR_MATCHING_DESCRIPTION_DATA: 'CLEAR_MATCHING_DESCRIPTION_DATA'
};
