export const transactionsConstants = {
    GET_TRANSACTIONS_REQUEST: 'GET_TRANSACTIONS_REQUEST',
    GET_TRANSACTIONS_SUCCESS: 'GET_TRANSACTIONS_SUCCESS',
    GET_TRANSACTIONS_FAILURE: 'GET_TRANSACTIONS_FAILURE',
    GET_TRANSACTIONS_TICKLIST: 'GET_TRANSACTIONS_TICKLIST',
    UPDATE_TRANSACTIONS_TICKLIST: 'UPDATE_TRANSACTIONS_TICKLIST',
    SET_TRANSACTIONS_SELECTED_ENTRIES: 'SET_TRANSACTIONS_SELECTED_ENTRIES',
    SET_TRANSACTIONS_MONTH: 'SET_TRANSACTIONS_MONTH',
    SET_TRANSACTIONS_YEAR: 'SET_TRANSACTIONS_YEAR',
    SET_TRANSACTION_SEARCH_QUERY: 'SET_TRANSACTION_SEARCH_QUERY',
    GET_TRANSACTION_SEARCH_QUERY: 'GET_TRANSACTION_SEARCH_QUERY'
};
